sudo: true
services:
  - docker
language: ruby
cache: bundler
rvm:
  - 2.3
before_install:
  - rake docker:pull
before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - rake build:all
deploy:
  provider: script
  script: rake docker:push
  on:
    branch: master
